
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideMenu from "./components/sideMenu/page";
import HeaderComponent from "./components/header/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

      <html lang="en">
        <body className={inter.className}>
          <div className="container">
            <div className="menu">
              <SideMenu />
            </div>
            
            <div className="main">
              <HeaderComponent />
              {children}
            </div>
          </div>
        </body>
      </html>
  );
}
