
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { SessionProvider } from "./components/SessionProvider";
import HeaderComponent from "./components/header/page";
import Footer from "./components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface Iprops {
  children: ReactNode;
  session: any;
}

export default function RootLayout({ children, session }: Iprops) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="container">
            <HeaderComponent/>
            <div className="main">
            {children}
            </div>
            <Footer/>
          </div>
          
          </SessionProvider>
      </body>
    </html>
  );
}
